name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.0.0
    - run: git fetch --prune --unshallow
    - name: Run Fury
      run: |
        ./fury build run --output linear --https
      timeout-minutes: 5

    - name: SBT action test
      id: sbt
      uses: lokkju/github-action-sbt@master
      with:
        commands: test
        sbt_project_directory: ./test
